### ISSUE TITLE
TypeError in Docker background jobs

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#1186]
```
workers_1         | 2017-06-01T16:35:24.015Z 1 TID-grbtmz6mc WARN: TypeError: no implicit conversion of nil into String
workers_1         | 2017-06-01T16:35:24.015Z 1 TID-grbtmz6mc WARN: /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/actors/hyrax/actors/file_set_actor.rb:120:in `basename'
workers_1         | /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/actors/hyrax/actors/file_set_actor.rb:120:in `label_for'
workers_1         | /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/actors/hyrax/actors/file_set_actor.rb:38:in `create_content'
workers_1         | /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/jobs/attach_files_to_work_job.rb:27:in `attach_content'
workers_1         | /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/jobs/attach_files_to_work_job.rb:14:in `block in perform'
web_1             | D, [2017-06-01T16:35:24.016202 #1] DEBUG -- : [e66bfb8c-b008-482e-897f-8004d1172384]   User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
workers_1         | /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/jobs/attach_files_to_work_job.rb:10:in `each'
workers_1         | /usr/local/bundle/bundler/gems/hyrax-731ac8607843/app/jobs/attach_files_to_work_job.rb:10:in `perform'
```

**Comment by jcoyne** [comment]
Here's what I'm seeing:

```
uploaded_file.file.file
=> #<CarrierWave::SanitizedFile:0x0055c49fc83c78 @file="/data/tmp/uploads/b6df8424-51b2-492d-bcc1-c84dc3418f73/hyrax/uploaded_file/file/1/dog.jpeg", @original_filename=nil, @content_type=nil>
uploaded_file.file.file.to_file
=> nil
uploaded_file.file.file.file
=> "/data/tmp/uploads/b6df8424-51b2-492d-bcc1-c84dc3418f73/hyrax/uploaded_file/file/1/dog.jpeg"
File.exist?(uploaded_file.file.file.file)
=> false
```

So, this likely a problem of not sharing the file system between the workers and web machines.
