### ISSUE TITLE
[docker] Fits MediaInfo issue

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#1274]
```
workers_1         | 2017-06-22T15:45:22.865Z 1 TID-gn466qwzc WARN: RuntimeError: Unable to execute command "/opt/fits-1.0.5/fits.sh -i "/data/tmp/uploads/f7301a1c-1c46-41df-8f8c-2266457295a5/hyrax/uploaded_file/file/4/AK-Page-4.pdf""
workers_1         | Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolException: Error loading native library for MediaInfo please check that fits_home is properly set
workers_1         | 	at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.<init>(MediaInfo.java:92)
workers_1         | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
workers_1         | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
workers_1         | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
workers_1         | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
workers_1         | 	at java.lang.Class.newInstance(Class.java:383)
workers_1         | 	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:136)
workers_1         | 	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:72)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:239)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:121)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:110)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:290)
workers_1         |
workers_1         | 2017-06-22T15:45:22.865Z 1 TID-gn466qwzc WARN: /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizer.rb:51:in `internal_call'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizer.rb:70:in `output'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizer.rb:22:in `call'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizers.rb:24:in `characterize_with'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:114:in `block in run_characterizers_on_file'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:113:in `map'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:113:in `run_characterizers_on_file'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:104:in `run_characterizers'
workers_1         | /usr/local/bundle/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:70:in `characterize'
workers_1         | /usr/local/bundle/gems/hydra-works-0.16.0/lib/hydra/works/services/characterization_service.rb:46:in `extract_metadata'
workers_1         | /usr/local/bundle/gems/hydra-works-0.16.0/lib/hydra/works/services/characterization_service.rb:29:in `characterize'
workers_1         | /usr/local/bundle/gems/hydra-works-0.16.0/lib/hydra/works/services/characterization_service.rb:10:in `run'
workers_1         | /usr/local/bundle/bundler/gems/hyrax-88753c7a9735/app/jobs/characterize_job.rb:12:in `perform'
```

**Comment by cldambrosio** [comment]
We solved this issue in our project by adding an environment variable pointing to the dependency: 
`LD_LIBRARY_PATH=/opt/fits-1.0.5/tools/mediainfo/linux`

With the current version of the [Dockerfile](https://github.com/samvera-labs/hyku/blob/master/Dockerfile) being
```FROM ruby:2.3.1
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs libreoffice imagemagick unzip ghostscript && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/fits && \
    curl -fSL -o /opt/fits-1.0.5.zip http://projects.iq.harvard.edu/files/fits/files/fits-1.0.5.zip && \
    cd /opt && unzip fits-1.0.5.zip && chmod +X fits-1.0.5/fits.sh

RUN mkdir /data
WORKDIR /data
ADD Gemfile /data/Gemfile
ADD Gemfile.lock /data/Gemfile.lock
RUN bundle install
ADD . /data
RUN bundle exec rake assets:precompile
EXPOSE 3000

**Comment by jcoyne** [comment]
@cldambrosio excellent. Good find. Can you make a pull request with that change?

**Comment by cldambrosio** [comment]
Sure :)

**Comment by suso2** [comment]
Thank you very much, cldambrosio!
It works for me.

**Comment by cldambrosio** [comment]
Very happy to help, thanks for letting me know @suso2 !
(sorry I just saw this- I was away on vacation)
