### ISSUE TITLE
Gateway Timeout 500 - Server did not responde

### ISSUE THREAD

**Issue by NickKmp** [samvera-labs/hyku#1316]
### Descriptive summary
After adding work with a number of files to a work the site gets an error as explained.

Include what commit of Hyku relates to this issue if appropriate, and any relevant tracebacks if you're reporting a bug.

### Expected behavior
Web server responds with list of the the works.

### Actual behavior

Error detailed below from the docker log

r@e8c9075[5c1eb80e-2fa5-4b8c-9072-fa68ce0e4c12_shard1_replica1] realtime]
solr_1            | 2017-07-02 02:23:17.923 INFO  (commitScheduler-37-thread-1) [c:5c1eb80e-2fa5-4b8c-9072-fa68ce0e4c12 s:shard1 r:core_node1 x:5c1eb80e-2fa5-4b8c-9072-fa68ce0e4c12_shard1_replica1] o.a.s.u.DirectUpdateHandler2 end_commit_flush
solr_1            | 2017-07-02 02:23:57.781 WARN  (zkCallback-4-thread-2-processing-n:172.18.0.10:8983_solr-SendThread(hyku_zoo2_1.hyku_internal:2181)) [   ] o.a.z.ClientCnxn Client session timed out, have not heard from server in 10357ms for sessionid 0x25d00e69c410000
solr_1            | 2017-07-02 02:24:38.779 WARN  (zkCallback-4-thread-2-processing-n:172.18.0.10:8983_solr-EventThread) [   ] o.a.s.c.c.ConnectionManager Watcher org.apache.solr.common.cloud.ConnectionManager@7e432568 name: ZooKeeperConnection Watcher:zookeeper_cluster:2181 got event WatchedEvent state:Disconnected type:None path:null path: null type: None
solr_1            | 2017-07-02 02:24:39.031 WARN  (zkCallback-4-thread-2-processing-n:172.18.0.10:8983_solr-EventThread) [   ] o.a.s.c.c.ConnectionManager zkClient has disconnected
zoo2_1            | 2017-07-02 02:23:11,837 [myid:2] - ERROR [LearnerHandler-/172.18.0.4:41110:LearnerHandler@648] - Unexpected exception causing shutdown while sock still open
zoo2_1            | java.net.SocketTimeoutException: Read timed out
zoo2_1            |     at java.net.SocketInputStream.socketRead0(Native Method)
zoo2_1            |     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
zoo2_1            |     at java.net.SocketInputStream.read(SocketInputStream.java:171)
zoo2_1            |     at java.net.SocketInputStream.read(SocketInputStream.java:141)
zoo2_1            |     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
zoo2_1            |     at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
zoo2_1            |     at java.io.DataInputStream.readInt(DataInputStream.java:387)
zoo2_1            |     at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)
zoo2_1            |     at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:83)
zoo2_1            |     at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)
zoo2_1            |     at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:559)
solr_1            | 2017-07-02 02:24:59.154 WARN  (zkCallback-4-thread-2-processing-n:172.18.0.10:8983_solr-SendThread(hyku_zoo1_1.hyku_internal:2181)) [   ] o.a.z.ClientCnxn Client session timed out, have not heard from server in 8577ms for sessionid 0x25d00e69c410000

### Steps to reproduce the behavior
Add a number of items to a work and then attempt to list the items in the work.

### Related work

Link to related tickets or prior related work here.

**Comment by NickKmp** [comment]
After some consideration this would appear memory related. Docker for windows was set at 2 GB and so memory allocation was increased to 5 GB. This has resulted in the initial 500 error being resolved.
