### ISSUE TITLE
Can't ingest CSV on AWS

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#220]
```
cd /var/app/current
./bin/import_from_csv baz.demo.hydrainabox.org spec/fixtures/csv/gse_metadata.csv
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/synchronized_minter.rb:43:in `initialize': Permission denied @ rb_sysopen - /tmp/minter-state (Errno::EACCES)
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/synchronized_minter.rb:43:in `open'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/synchronized_minter.rb:43:in `next_id'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/synchronized_minter.rb:15:in `block in mint'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/synchronized_minter.rb:13:in `synchronize'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/synchronized_minter.rb:13:in `mint'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/active_fedora-noid-1.1.0/lib/active_fedora/noid/service.rb:17:in `mint'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/services/curation_concerns/noid.rb:10:in `assign_id'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/assign_identifier_actor.rb:5:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/base_actor.rb:15:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/interpret_visibility_actor.rb:73:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/abstract_actor.rb:25:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/attach_files_actor.rb:7:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/assign_representative_actor.rb:5:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/add_to_collection_actor.rb:6:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /home/ec2-user/.gem/ruby/2.3.0/bundler/gems/sufia-1e30e56b5683/app/actors/sufia/create_with_files_actor.rb:6:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /home/ec2-user/.gem/ruby/2.3.0/bundler/gems/sufia-1e30e56b5683/app/actors/sufia/create_with_remote_files_actor.rb:6:in `create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/curation_concerns-1.0.0.beta4/app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
    from /var/app/current/lib/importer/factory/object_factory.rb:97:in `block (2 levels) in create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /var/app/current/lib/importer/factory/object_factory.rb:90:in `block in create'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /var/app/current/lib/importer/factory/object_factory.rb:89:in `create'
    from /var/app/current/lib/importer/factory/object_factory.rb:30:in `block in run'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
    from /var/app/current/lib/importer/factory/object_factory.rb:28:in `run'
    from /var/app/current/lib/importer/csv_importer.rb:34:in `create_fedora_objects'
    from /var/app/current/lib/importer/csv_importer.rb:15:in `block in import_all'
    from /var/app/current/lib/importer/csv_parser.rb:16:in `block in each'
    from /opt/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1748:in `each'
    from /opt/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1131:in `block in foreach'
    from /opt/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1282:in `open'
    from /opt/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1130:in `foreach'
    from /var/app/current/lib/importer/csv_parser.rb:13:in `each'
    from /var/app/current/lib/importer/csv_importer.rb:14:in `import_all'
    from ./bin/import_from_csv:36:in `main'
    from ./bin/import_from_csv:45:in `<main>'
```

**Comment by cbeer** [comment]
Hm. I guess we ought to serialize and store the minter state on some shared storage (redis? memcache? s3?)

**Comment by jcoyne** [comment]
Probably a good idea, however for this issue, it shouldn't even try the minter as I'm supplying an id (the druid)

**Comment by jcoyne** [comment]
I think this will fix it https://github.com/projecthydra/curation_concerns/pull/822

**Comment by mjgiarlo** [comment]
This is outdated.
