### ISSUE TITLE
IngestFileJob is sometimes failing on AWS

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#722]
```
I, [2017-01-28T17:55:35.971782 #24602]  INFO -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f] [ActiveJob] [IngestFileJob] [6169268e-0ce4-41ce-a449-a36195158d11] Performing IngestFileJob from BetterActiveElasticJob(default) with arguments: #<GlobalID:0x007fb1fc982e10 @uri=#<URI::GID gid://hyku/FileSet/6q182k12h>>, "/tmp/6q182k12h20170128-24602-1y3ld5", #<GlobalID:0x007fb1fc981cb8 @uri=#<URI::GID gid://hyku/User/1>>, {:relation=>"original_file"}
I, [2017-01-28T17:55:35.972052 #24602]  INFO -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f] [ActiveJob] [IngestFileJob] [6169268e-0ce4-41ce-a449-a36195158d11] Performed IngestFileJob from BetterActiveElasticJob(default) in 0.18ms
D, [2017-01-28T17:55:35.976981 #24602] DEBUG -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f]   [1m[36mAccount Load (1.4ms)[0m  [1m[34mSELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2[0m  [["tenant", "public"], ["LIMIT", 1]]
F, [2017-01-28T17:55:35.977876 #24602] FATAL -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f]   
F, [2017-01-28T17:55:35.977916 #24602] FATAL -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f] Errno::ENOENT (No such file or directory @ rb_sysopen - /tmp/6q182k12h20170128-24602-1y3ld5):
F, [2017-01-28T17:55:35.977953 #24602] FATAL -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f]   
F, [2017-01-28T17:55:35.977974 #24602] FATAL -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f] lib/active_job_tenant.rb:26:in `block in perform_now'
[2b49bb60-5116-484a-869a-8547e7a4fa1f] lib/active_job_tenant.rb:42:in `block in switch'
[2b49bb60-5116-484a-869a-8547e7a4fa1f] lib/active_job_tenant.rb:41:in `switch'
[2b49bb60-5116-484a-869a-8547e7a4fa1f] lib/active_job_tenant.rb:25:in `perform_now'
D, [2017-01-28T17:55:35.978083 #24602] DEBUG -- : [2b49bb60-5116-484a-869a-8547e7a4fa1f] Error occurred while parsing request parameters.
Contents:
```

**Comment by hannahfrost** [comment]
This is old.
