### ISSUE TITLE
Solr down on aws

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#724]
Unable to write to solr, however solr reads seem to work.

```
F, [2017-01-30T15:13:14.888549 #24713] FATAL -- : [27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] RSolr::Error::Http (RSolr::Error::Http - 503 Service Unavailable
Error: 'Cannot talk to ZooKeeper - Updates are disabled.','code'=>503}}

URI: http://solr.demo.vpc.hydrainabox.org/solr/52ffafc8-a4f7-4061-80f6-f21863158e8e/update?wt=ruby&softCommit=true
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"system_create_dtsi\">2017-01-30T15:13:14Z</field><field name=\"system_modified_dtsi\">2017-01-30T15:13:14Z</field><field name=\"has_model_ssim\">Hydra::AccessControl</field><field name=\"id\">af888c44-e627-42e5-86cc-e58f35aabf6f</field></doc></add>"

Backtrace: /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `post'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:84:in `update'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:104:in `add'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/solr_service.rb:72:in `add'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/indexing.rb:42:in `update_index'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/indexing.rb:64:in `_create_record'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/callbacks.rb:240:in `block in _create_record'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'):
F, [2017-01-30T15:13:14.888587 #24713] FATAL -- : [27b3f029-4fcb-4b81-87b4-27f28f6f1a6d]   
F, [2017-01-30T15:13:14.888629 #24713] FATAL -- : [27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rsolr (1.1.2) lib/rsolr/client.rb:288:in `adapt_response'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rsolr (1.1.2) lib/rsolr/client.rb:189:in `execute'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rsolr (1.1.2) lib/rsolr/client.rb:175:in `send_and_receive'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] (eval):2:in `post'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rsolr (1.1.2) lib/rsolr/client.rb:84:in `update'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rsolr (1.1.2) lib/rsolr/client.rb:104:in `add'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/solr_service.rb:72:in `add'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/indexing.rb:42:in `update_index'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/indexing.rb:64:in `_create_record'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/callbacks.rb:240:in `block in _create_record'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/callbacks.rb:240:in `_create_record'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/persistence.rb:159:in `create_or_update'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/callbacks.rb:236:in `block in create_or_update'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/callbacks.rb:236:in `create_or_update'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/persistence.rb:29:in `save'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/validations.rb:50:in `save'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/persistence.rb:123:in `create'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/reflection.rb:281:in `create_association'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/associations/singular_association.rb:47:in `new_record'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/associations/singular_association.rb:21:in `create'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/associations/builder/singular_association.rb:18:in `block in define_constructors'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:25:in `permission_delegate'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:18:in `permissions'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:420:in `search_by_mode'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:410:in `search_by_type_and_mode'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:172:in `read_groups'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:183:in `read_groups='
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/hyrax-88a67fd52455/app/services/hyrax/admin_set_create_service.rb:24:in `create'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/hyrax-88a67fd52455/app/services/hyrax/admin_set_create_service.rb:9:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/hyrax-88a67fd52455/app/controllers/hyrax/admin/admin_sets_controller.rb:98:in `create_admin_set'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/hyrax-88a67fd52455/app/controllers/hyrax/admin/admin_sets_controller.rb:63:in `create'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/engine.rb:522:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/railtie.rb:193:in `public_send'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/railtie.rb:193:in `method_missing'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] peek-performance_bar (1.2.1) lib/peek/views/performance_bar/process_utilization.rb:144:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] is_it_working (1.1.0) lib/is_it_working/handler.rb:48:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] apartment (1.2.0) lib/apartment/elevators/generic.rb:22:in `block in call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] apartment (1.2.0) lib/apartment/adapters/abstract_adapter.rb:106:in `switch'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] apartment (1.2.0) lib/apartment/elevators/generic.rb:22:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] warden (1.2.6) lib/warden/manager.rb:34:in `catch'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] warden (1.2.6) lib/warden/manager.rb:34:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/etag.rb:25:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/head.rb:12:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/active_fedora-c49373d9b0e0/lib/active_fedora/ldp_cache.rb:26:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/flipflop-0eecddade989/lib/flipflop/feature_cache.rb:12:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/method_override.rb:22:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/runtime.rb:22:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] secure_headers (3.6.1) lib/secure_headers/middleware.rb:12:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] railties (5.0.1) lib/rails/engine.rb:522:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] puma (3.6.2) lib/puma/configuration.rb:225:in `call'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] puma (3.6.2) lib/puma/server.rb:415:in `process_client'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] puma (3.6.2) lib/puma/server.rb:275:in `block in run'
[27b3f029-4fcb-4b81-87b4-27f28f6f1a6d] puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by atz** [comment]
Bill says this is still open because it is understood that if we ran a big ingest job again, it would knock solr down again.  Some changes in the works are intended to improve stability.

**Comment by atz** [comment]
@bbranan update?

**Comment by mjgiarlo** [comment]
@bbranan @eefahy Do y'all consider this in progress?

**Comment by bbranan** [comment]
@eefahy has started work to transition deployment of Solr and Zookeeper to Beanstalk, see: https://github.com/hybox/aws/issues/125 and https://github.com/hybox/aws/issues/126.

**Comment by mjgiarlo** [comment]
@bbranan @eefahy Do you think we'll get to this ticket (and the two linked above) in advance of the public beta test on May 15th? Or is it a medium-term target?

**Comment by eefahy** [comment]
I'm working on this as we speak. It's a big job though so I'm hesitant to say that everything will be ready and sold by May 15th however, we know how to keep the solr connection stable in ECS (the old way)

**Comment by mjgiarlo** [comment]
@eefahy Can this be closed now?
